EGC2425-RaboDeToro-hub/RaboDeToro-hub-1

app/modules/explore/repositories.py
app/modules/explore/tests/test_selenium.py
app/modules/explore/tests/test_unit.py

Se han añadido tests unitarios y de selenium  para la nueva funcionalidad de improve search que consiste en aplicar dos nuevos filtros de búsqueda con fechas y tamaño.
Refs #8

test: Añadir tests para improve search

---

migrations/versions/d4a800c1ebcf_merging_heads.py

Se han arreglado las migraciones que faltaban

fix: Arreglar migraciones

---

.github/workflows/commit.yml
.github/workflows/test.yml

Se han añadido workflows para test y commit.
Refs #34

feat: Añadir nuevos workflows

---

.github/workflows/commit.yml
.github/workflows/render.yml

Se han modificado los workflows correspondientes.
Refs #34

fix: Modificar commit y render

---

.github/ISSUE_TEMPLATES/issue_technical_task_template.yml
.github/ISSUE_TEMPLATES/issue_work_item_template.yml

Añadidas plantilas para issue sobre WI y tareas tecnicas.
Refs #46

feat: Añadir plantillas issue

---

.gitignore
app/modules/auth/routes.py
app/modules/dataset/api.py
app/modules/dataset/models.py
app/modules/dataset/repositories.py
app/modules/dataset/routes.py
app/modules/dataset/services.py
app/modules/dataset/tests/locustfile.py
app/modules/dataset/tests/test_integration.py
app/modules/dataset/tests/test_selenium.py
app/modules/dataset/tests/test_unit.py
app/modules/email/services.py
app/modules/explore/repositories.py
app/modules/explore/routes.py
app/modules/explore/tests/test_unit.py
app/modules/forgotPassword/models.py
app/modules/forgotPassword/routes.py
app/modules/forgotPassword/services.py
app/modules/profile/routes.py

Se han limpiado todos los archivos dentro del directorio app para evitar problemas de lint
Refs#null

style: lint limpiado

---

app/modules/community/tests/test_integration.py
app/modules/community/tests/test_selenium.py

Se han añadido tests de integracion del modulo de comunidades
Refs#27

test: community tests

---

app/modules/community/tests/test_selenium.py

Se han arreglado los tests de selenium del modulo de comunidades
Refs#null

test: Test de comunidad arreglados

---

.github/workflows/commit.yml

Se ha arreglado el workflow commit.
Refs #34

fix: Arreglar workflow

---

README.md

Se ha actualizado el Readme con nueva información y nuevo lenguaje añadido.
Refs #null

docs: Actualizar Readme

---

.vscode/settings.json

no se pueden tener carpetas de IDEs

style: Eliminar .vscode

---

vagrant/02_install_mariadb.yml

fix: vagrant

---

.github/workflows/codacy2.yml
.github/workflows/render.yml

Se ha arreglado codacy y render.
Refs #null

fix: Arreglar workflows

---

.github/hooks/commit-msg

Se ha perfeccionado el formato del comit a validar.
Refs#null

fix: Corregir weebkook

---

app/modules/fakenodo/services.py
app/modules/fakenodo/tests/test_unit.py

test: fakenodo.

---

app/modules/dataset/services.py
app/modules/dataset/tests/test_unit.py

Añadida descarga de todos los formatos del dataset, y de mas test unitarios.

Hotfix/download all dataset/6

---

app/modules/explore/tests/test_selenium.py

tests de selinium arreglados.
Refs#null

fix: explore tests

---

app/modules/dataset/seeders.py

Modificado seeders para contar bien las caracteristicas.
Refs #20

fix: Modificar seeders

---

app/modules/dataset/templates/dataset/list_datasets.html

Arreglado list_datasets para que no de error 500.
Refs #null

fix: Arreglo listado dataset

---

app/modules/dataset/tests/test_selenium.py

Se ha añadido el test upload dataset.
Refs #null

feat: Añadir test upload

---

.github/workflows/render.yml

fix: Update render.yml

---

.github/workflows/render.yml

style: Update render.yml

---

.github/workflows/render.yml

fix: render

---

docker/entrypoints/render_entrypoint.sh

fix: reder entrypoint

---

setup.sh

fix: setup

---

app/modules/public/templates/public/index.html
setup.sh

Pasar cambios a main.
Refs#null.

feat: Develop
